import { head, layoutCSS, sidebar } from "./shared";

export function getDashboardPage() {
  const css = layoutCSS() + `.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:16px;margin-bottom:40px;}.card{background:rgba(15,15,23,.6);border:1px solid rgba(148,163,184,.06);border-radius:16px;padding:24px;transition:all .2s;}.card:hover{border-color:rgba(148,163,184,.12);transform:translateY(-2px);}.card .lbl{font-size:11px;font-weight:600;text-transform:uppercase;letter-spacing:.8px;color:#64748b;margin-bottom:12px;}.card .val{font-size:32px;font-weight:800;letter-spacing:-.03em;}.card.green .val{color:#34d399;}.card.red .val{color:#f87171;}.card.blue .val{color:#60a5fa;}.svc-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(300px,1fr));gap:14px;}.svc{background:rgba(15,15,23,.6);border:1px solid rgba(148,163,184,.06);border-radius:14px;padding:20px 24px;display:flex;align-items:center;justify-content:space-between;transition:all .2s;}.svc:hover{border-color:rgba(148,163,184,.12);}.svc .name{display:flex;align-items:center;gap:10px;font-size:14px;font-weight:600;color:#e2e8f0;}.svc .dot{width:8px;height:8px;border-radius:50%;flex-shrink:0;}.svc .dot.on{background:#34d399;box-shadow:0 0 8px rgba(52,211,153,.4);}.svc .dot.off{background:#f87171;}.svc .nums{display:flex;gap:16px;font-size:12px;color:#64748b;}.svc .nums b{color:#e2e8f0;font-weight:600;}`;

  return head("Dashboard — Log Admin", css) + `<body><div class="shell">${sidebar("dashboard")}<main class="main"><h1>Dashboard</h1><p class="desc">Real-time overview of all service logs</p><div class="cards" id="cards"></div><h2 style="font-size:15px;font-weight:600;color:#94a3b8;margin-bottom:16px;">Services</h2><div class="svc-grid" id="svcs"></div></main></div><script>
async function load(){const r=await fetch('/api/stats');const d=await r.json();
document.getElementById('cards').innerHTML=\`<div class="card green"><div class="lbl">Total Logs Today</div><div class="val">\${d.totalRequests.toLocaleString()}</div></div><div class="card red"><div class="lbl">Errors Today</div><div class="val">\${d.totalErrors.toLocaleString()}</div></div><div class="card blue"><div class="lbl">Active Services</div><div class="val">\${d.services}</div></div>\`;
document.getElementById('svcs').innerHTML=Object.entries(d.stats).map(([n,s])=>\`<div class="svc"><div class="name"><span class="dot \${s.available?'on':'off'}"></span>\${n}</div><div class="nums"><span>Logs: <b>\${s.requests}</b></span><span>Errors: <b style="color:\${s.errors>0?'#f87171':'inherit'}">\${s.errors}</b></span></div></div>\`).join('')}
load();setInterval(load,15000);</script></body></html>`;
}
